
services:
  api-gateway:
    build:
      context: ./Streetcode/Services/Streetcode.ApiGateway/Streetcode.ApiGateway
    container_name: Streetcode-Api-Gateway
    ports:
      - "8082:8082"
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    build:
      context: .
    container_name: Streetcode-Server
    ports:
        - "5001:80"
    depends_on:
        - mssql
    environment:
      - ASPNETCORE_ENVIRONMENT=Local
    networks:
      - app-network

  frontend:
    build:
      context: ../Streetcode-Client-November-2025
    container_name: Streetcode-Client
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - app-network

  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: Streetcode-Database
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=${DOCKER_DB_PASSWD}
      - MSSQL_PID=Developer
    ports:
      - "5434:1433"
    networks:
      - app-network

  redis:
    image: redis:7-alpine
    container_name: Streetcode-Redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - app-network
    command: redis-server --appendonly yes

networks:
  app-network:
    driver: bridge

volumes:
  redis-data:  