//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Streetcode.BLL {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ErrorMessages {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMessages() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Streetcode.BLL.ErrorMessages", typeof(ErrorMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string NewsNotFoundByUrl {
            get {
                return ResourceManager.GetString("NewsNotFoundByUrl", resourceCulture);
            }
        }
        
        internal static string StreetcodeCreationFailed {
            get {
                return ResourceManager.GetString("StreetcodeCreationFailed", resourceCulture);
            }
        }
        
        internal static string ValidationException {
            get {
                return ResourceManager.GetString("ValidationException", resourceCulture);
            }
        }
        
        internal static string IdMustBeGreaterThan {
            get {
                return ResourceManager.GetString("IdMustBeGreaterThan", resourceCulture);
            }
        }
        
        internal static string ArtsNotFound {
            get {
                return ResourceManager.GetString("ArtsNotFound", resourceCulture);
            }
        }
        
        internal static string ArtNotFoundById {
            get {
                return ResourceManager.GetString("ArtNotFoundById", resourceCulture);
            }
        }
        
        internal static string ArtNotFoundByStreetcodeId {
            get {
                return ResourceManager.GetString("ArtNotFoundByStreetcodeId", resourceCulture);
            }
        }
        
        internal static string AudioBase64Required {
            get {
                return ResourceManager.GetString("AudioBase64Required", resourceCulture);
            }
        }
        
        internal static string AudioBase64Invalid {
            get {
                return ResourceManager.GetString("AudioBase64Invalid", resourceCulture);
            }
        }
        
        internal static string AudioSizeExceeded {
            get {
                return ResourceManager.GetString("AudioSizeExceeded", resourceCulture);
            }
        }
        
        internal static string AudioExtensionRequired {
            get {
                return ResourceManager.GetString("AudioExtensionRequired", resourceCulture);
            }
        }
        
        internal static string AudioExtensionInvalid {
            get {
                return ResourceManager.GetString("AudioExtensionInvalid", resourceCulture);
            }
        }
        
        internal static string MimeTypeTooLong {
            get {
                return ResourceManager.GetString("MimeTypeTooLong", resourceCulture);
            }
        }
        
        internal static string TitleTooLong {
            get {
                return ResourceManager.GetString("TitleTooLong", resourceCulture);
            }
        }
        
        internal static string DescriptionTooLong {
            get {
                return ResourceManager.GetString("DescriptionTooLong", resourceCulture);
            }
        }
        
        internal static string AudioDataRequired {
            get {
                return ResourceManager.GetString("AudioDataRequired", resourceCulture);
            }
        }
        
        internal static string AudioCreationFailed {
            get {
                return ResourceManager.GetString("AudioCreationFailed", resourceCulture);
            }
        }
        
        internal static string AudioDeletionFailed {
            get {
                return ResourceManager.GetString("AudioDeletionFailed", resourceCulture);
            }
        }
        
        internal static string AudioNotFoundById {
            get {
                return ResourceManager.GetString("AudioNotFoundById", resourceCulture);
            }
        }
        
        internal static string AudiosNotFound {
            get {
                return ResourceManager.GetString("AudiosNotFound", resourceCulture);
            }
        }
        
        internal static string AudioNotFoundByStreetcodeId {
            get {
                return ResourceManager.GetString("AudioNotFoundByStreetcodeId", resourceCulture);
            }
        }
        
        internal static string ImageDataRequired {
            get {
                return ResourceManager.GetString("ImageDataRequired", resourceCulture);
            }
        }
        
        internal static string ImageBase64Required {
            get {
                return ResourceManager.GetString("ImageBase64Required", resourceCulture);
            }
        }
        
        internal static string ImageBase64Invalid {
            get {
                return ResourceManager.GetString("ImageBase64Invalid", resourceCulture);
            }
        }
        
        internal static string ImageSizeExceeded {
            get {
                return ResourceManager.GetString("ImageSizeExceeded", resourceCulture);
            }
        }
        
        internal static string ImageExtensionRequired {
            get {
                return ResourceManager.GetString("ImageExtensionRequired", resourceCulture);
            }
        }
        
        internal static string ImageExtensionInvalid {
            get {
                return ResourceManager.GetString("ImageExtensionInvalid", resourceCulture);
            }
        }
        
        internal static string AltTextTooLong {
            get {
                return ResourceManager.GetString("AltTextTooLong", resourceCulture);
            }
        }
        
        internal static string InvalidImageFormat {
            get {
                return ResourceManager.GetString("InvalidImageFormat", resourceCulture);
            }
        }
        
        internal static string ImageCreationFailed {
            get {
                return ResourceManager.GetString("ImageCreationFailed", resourceCulture);
            }
        }
        
        internal static string ImageIdMustBeGreaterThanZero {
            get {
                return ResourceManager.GetString("ImageIdMustBeGreaterThanZero", resourceCulture);
            }
        }
        
        internal static string ImageNotFoundByCategoryId {
            get {
                return ResourceManager.GetString("ImageNotFoundByCategoryId", resourceCulture);
            }
        }
        
        internal static string ImageDeletionFailed {
            get {
                return ResourceManager.GetString("ImageDeletionFailed", resourceCulture);
            }
        }
        
        internal static string ImageNotFound {
            get {
                return ResourceManager.GetString("ImageNotFound", resourceCulture);
            }
        }
        
        internal static string ImageNotFoundById {
            get {
                return ResourceManager.GetString("ImageNotFoundById", resourceCulture);
            }
        }
        
        internal static string ImageNotFoundByStreetcodeId {
            get {
                return ResourceManager.GetString("ImageNotFoundByStreetcodeId", resourceCulture);
            }
        }
        
        internal static string VideosNotFound {
            get {
                return ResourceManager.GetString("VideosNotFound", resourceCulture);
            }
        }
        
        internal static string StreetcodeNotFoundById {
            get {
                return ResourceManager.GetString("StreetcodeNotFoundById", resourceCulture);
            }
        }
        
        internal static string VideoNotFoundById {
            get {
                return ResourceManager.GetString("VideoNotFoundById", resourceCulture);
            }
        }
        
        internal static string NewsTitleRequired {
            get {
                return ResourceManager.GetString("NewsTitleRequired", resourceCulture);
            }
        }
        
        internal static string NewsTitleTooLong {
            get {
                return ResourceManager.GetString("NewsTitleTooLong", resourceCulture);
            }
        }
        
        internal static string NewsTextRequired {
            get {
                return ResourceManager.GetString("NewsTextRequired", resourceCulture);
            }
        }
        
        internal static string NewsUrlRequired {
            get {
                return ResourceManager.GetString("NewsUrlRequired", resourceCulture);
            }
        }
        
        internal static string NewsUrlTooLong {
            get {
                return ResourceManager.GetString("NewsUrlTooLong", resourceCulture);
            }
        }
        
        internal static string NewsCreationDateRequired {
            get {
                return ResourceManager.GetString("NewsCreationDateRequired", resourceCulture);
            }
        }
        
        internal static string NewsCreationDateInFuture {
            get {
                return ResourceManager.GetString("NewsCreationDateInFuture", resourceCulture);
            }
        }
        
        internal static string NewsDataRequired {
            get {
                return ResourceManager.GetString("NewsDataRequired", resourceCulture);
            }
        }
        
        internal static string NewsCreationFailed {
            get {
                return ResourceManager.GetString("NewsCreationFailed", resourceCulture);
            }
        }
        
        internal static string NewsConversionFailed {
            get {
                return ResourceManager.GetString("NewsConversionFailed", resourceCulture);
            }
        }
        
        internal static string NewsIdMustBeGreaterThanZero {
            get {
                return ResourceManager.GetString("NewsIdMustBeGreaterThanZero", resourceCulture);
            }
        }
        
        internal static string NewsNotFoundById {
            get {
                return ResourceManager.GetString("NewsNotFoundById", resourceCulture);
            }
        }
        
        internal static string NewsDeletionFailed {
            get {
                return ResourceManager.GetString("NewsDeletionFailed", resourceCulture);
            }
        }
        
        internal static string NewsNotFound {
            get {
                return ResourceManager.GetString("NewsNotFound", resourceCulture);
            }
        }
        
        internal static string NewsUpdateFailed {
            get {
                return ResourceManager.GetString("NewsUpdateFailed", resourceCulture);
            }
        }
        
        internal static string PartnerDataRequired {
            get {
                return ResourceManager.GetString("PartnerDataRequired", resourceCulture);
            }
        }
        
        internal static string PartnerTitleRequired {
            get {
                return ResourceManager.GetString("PartnerTitleRequired", resourceCulture);
            }
        }
        
        internal static string PartnerLogoIdMustBeGreaterThanZero {
            get {
                return ResourceManager.GetString("PartnerLogoIdMustBeGreaterThanZero", resourceCulture);
            }
        }
        
        internal static string PartnerStreetcodesRequired {
            get {
                return ResourceManager.GetString("PartnerStreetcodesRequired", resourceCulture);
            }
        }
        
        internal static string PartnerTitleTooLong {
            get {
                return ResourceManager.GetString("PartnerTitleTooLong", resourceCulture);
            }
        }
        
        internal static string PartnerDescriptionTooLong {
            get {
                return ResourceManager.GetString("PartnerDescriptionTooLong", resourceCulture);
            }
        }
        
        internal static string PartnerUrlTitleTooLong {
            get {
                return ResourceManager.GetString("PartnerUrlTitleTooLong", resourceCulture);
            }
        }
        
        internal static string PartnerTargetUrlInvalid {
            get {
                return ResourceManager.GetString("PartnerTargetUrlInvalid", resourceCulture);
            }
        }
        
        internal static string PartnerTitleAlreadyExists {
            get {
                return ResourceManager.GetString("PartnerTitleAlreadyExists", resourceCulture);
            }
        }
        
        internal static string PartnerIdMustBeGreaterThanZero {
            get {
                return ResourceManager.GetString("PartnerIdMustBeGreaterThanZero", resourceCulture);
            }
        }
        
        internal static string PartnerNotFound {
            get {
                return ResourceManager.GetString("PartnerNotFound", resourceCulture);
            }
        }
        
        internal static string PartnerNotFoundById {
            get {
                return ResourceManager.GetString("PartnerNotFoundById", resourceCulture);
            }
        }
        
        internal static string PartnersNotFoundByStreetcodeId {
            get {
                return ResourceManager.GetString("PartnersNotFoundByStreetcodeId", resourceCulture);
            }
        }
        
        internal static string PaymentAmountMustBeGreaterThanZero {
            get {
                return ResourceManager.GetString("PaymentAmountMustBeGreaterThanZero", resourceCulture);
            }
        }
        
        internal static string PaymentAmountExceeded {
            get {
                return ResourceManager.GetString("PaymentAmountExceeded", resourceCulture);
            }
        }
        
        internal static string PaymentRedirectUrlTooLong {
            get {
                return ResourceManager.GetString("PaymentRedirectUrlTooLong", resourceCulture);
            }
        }
        
        internal static string PaymentRedirectUrlInvalid {
            get {
                return ResourceManager.GetString("PaymentRedirectUrlInvalid", resourceCulture);
            }
        }
        
        internal static string PaymentDataRequired {
            get {
                return ResourceManager.GetString("PaymentDataRequired", resourceCulture);
            }
        }
        
        internal static string StreetcodeDataRequired {
            get {
                return ResourceManager.GetString("StreetcodeDataRequired", resourceCulture);
            }
        }
        
        internal static string CategoryNotFoundById {
            get {
                return ResourceManager.GetString("CategoryNotFoundById", resourceCulture);
            }
        }
        
        internal static string CategoryNotFoundByStreetcodeId {
            get {
                return ResourceManager.GetString("CategoryNotFoundByStreetcodeId", resourceCulture);
            }
        }
        
        internal static string CategoriesNotFound {
            get {
                return ResourceManager.GetString("CategoriesNotFound", resourceCulture);
            }
        }
        
        internal static string FactTitleAlreadyExists {
            get {
                return ResourceManager.GetString("FactTitleAlreadyExists", resourceCulture);
            }
        }
        
        internal static string FactMappingFailed {
            get {
                return ResourceManager.GetString("FactMappingFailed", resourceCulture);
            }
        }
        
        internal static string StreetcodeIdMustBeGreaterThanZero {
            get {
                return ResourceManager.GetString("StreetcodeIdMustBeGreaterThanZero", resourceCulture);
            }
        }
        
        internal static string FactDataRequired {
            get {
                return ResourceManager.GetString("FactDataRequired", resourceCulture);
            }
        }
        
        internal static string FactNotFound {
            get {
                return ResourceManager.GetString("FactNotFound", resourceCulture);
            }
        }
        
        internal static string FactIdMustBeGreaterThanZero {
            get {
                return ResourceManager.GetString("FactIdMustBeGreaterThanZero", resourceCulture);
            }
        }
        
        internal static string FactNotFoundById {
            get {
                return ResourceManager.GetString("FactNotFoundById", resourceCulture);
            }
        }
        
        internal static string FactNotFoundByStreetcodeId {
            get {
                return ResourceManager.GetString("FactNotFoundByStreetcodeId", resourceCulture);
            }
        }
        
        internal static string FactTitleRequired {
            get {
                return ResourceManager.GetString("FactTitleRequired", resourceCulture);
            }
        }
        
        internal static string FactTitleTooLong {
            get {
                return ResourceManager.GetString("FactTitleTooLong", resourceCulture);
            }
        }
        
        internal static string FactContentRequired {
            get {
                return ResourceManager.GetString("FactContentRequired", resourceCulture);
            }
        }
        
        internal static string FactContentTooLong {
            get {
                return ResourceManager.GetString("FactContentTooLong", resourceCulture);
            }
        }
        
        internal static string FactImageIdMustBeGreaterThanZero {
            get {
                return ResourceManager.GetString("FactImageIdMustBeGreaterThanZero", resourceCulture);
            }
        }
        
        internal static string RelatedFigureCreationFailed {
            get {
                return ResourceManager.GetString("RelatedFigureCreationFailed", resourceCulture);
            }
        }
        
        internal static string RelatedFigureObserverIdMustBeGreaterThanZero {
            get {
                return ResourceManager.GetString("RelatedFigureObserverIdMustBeGreaterThanZero", resourceCulture);
            }
        }
        
        internal static string RelatedFigureTargetIdMustBeGreaterThanZero {
            get {
                return ResourceManager.GetString("RelatedFigureTargetIdMustBeGreaterThanZero", resourceCulture);
            }
        }
        
        internal static string RelatedFigureSelfReferenceNotAllowed {
            get {
                return ResourceManager.GetString("RelatedFigureSelfReferenceNotAllowed", resourceCulture);
            }
        }
        
        internal static string RelatedFigureNotFound {
            get {
                return ResourceManager.GetString("RelatedFigureNotFound", resourceCulture);
            }
        }
        
        internal static string RelatedFigureDeletionFailed {
            get {
                return ResourceManager.GetString("RelatedFigureDeletionFailed", resourceCulture);
            }
        }
        
        internal static string StreetcodeNotFoundByTagId {
            get {
                return ResourceManager.GetString("StreetcodeNotFoundByTagId", resourceCulture);
            }
        }
        
        internal static string RelatedTermWordRequired {
            get {
                return ResourceManager.GetString("RelatedTermWordRequired", resourceCulture);
            }
        }
        
        internal static string RelatedTermWordTooLong {
            get {
                return ResourceManager.GetString("RelatedTermWordTooLong", resourceCulture);
            }
        }
        
        internal static string RelatedTermTermIdMustBeGreaterThanZero {
            get {
                return ResourceManager.GetString("RelatedTermTermIdMustBeGreaterThanZero", resourceCulture);
            }
        }
        
        internal static string RelatedTermWordAlreadyExists {
            get {
                return ResourceManager.GetString("RelatedTermWordAlreadyExists", resourceCulture);
            }
        }
        
        internal static string CannotMapEntity {
            get {
                return ResourceManager.GetString("CannotMapEntity", resourceCulture);
            }
        }
        
        internal static string RelatedTermDataRequired {
            get {
                return ResourceManager.GetString("RelatedTermDataRequired", resourceCulture);
            }
        }
        
        internal static string RelatedTermWordForDeletionRequired {
            get {
                return ResourceManager.GetString("RelatedTermWordForDeletionRequired", resourceCulture);
            }
        }
        
        internal static string RelatedTermDeletionFailed {
            get {
                return ResourceManager.GetString("RelatedTermDeletionFailed", resourceCulture);
            }
        }
        
        internal static string RelatedTermNotFound {
            get {
                return ResourceManager.GetString("RelatedTermNotFound", resourceCulture);
            }
        }
        
        internal static string RelatedTermsNotFoundByTermId {
            get {
                return ResourceManager.GetString("RelatedTermsNotFoundByTermId", resourceCulture);
            }
        }
        
        internal static string RelatedTermsMappingFailed {
            get {
                return ResourceManager.GetString("RelatedTermsMappingFailed", resourceCulture);
            }
        }
        
        internal static string WrongJSONStructure {
            get {
                return ResourceManager.GetString("WrongJSONStructure", resourceCulture);
            }
        }
        
        internal static string StreetcodeIndexRequired {
            get {
                return ResourceManager.GetString("StreetcodeIndexRequired", resourceCulture);
            }
        }
        
        internal static string StreetcodeTypeRequired {
            get {
                return ResourceManager.GetString("StreetcodeTypeRequired", resourceCulture);
            }
        }
        
        internal static string StreetcodeTitleRequired {
            get {
                return ResourceManager.GetString("StreetcodeTitleRequired", resourceCulture);
            }
        }
        
        internal static string StreetcodeEventStartOrPersonBirthDateRequired {
            get {
                return ResourceManager.GetString("StreetcodeEventStartOrPersonBirthDateRequired", resourceCulture);
            }
        }
        
        internal static string StreetcodeTransliterationUrlRequired {
            get {
                return ResourceManager.GetString("StreetcodeTransliterationUrlRequired", resourceCulture);
            }
        }
        
        internal static string StreetcodeIndexMustBeInteger {
            get {
                return ResourceManager.GetString("StreetcodeIndexMustBeInteger", resourceCulture);
            }
        }
        
        internal static string StreetcodeTypeInvalid {
            get {
                return ResourceManager.GetString("StreetcodeTypeInvalid", resourceCulture);
            }
        }
        
        internal static string StreetcodeEventStartOrPersonBirthDateInvalid {
            get {
                return ResourceManager.GetString("StreetcodeEventStartOrPersonBirthDateInvalid", resourceCulture);
            }
        }
        
        internal static string StreetcodeEventEndOrPersonDeathDateInvalid {
            get {
                return ResourceManager.GetString("StreetcodeEventEndOrPersonDeathDateInvalid", resourceCulture);
            }
        }
        
        internal static string StreetcodeAudioIdMustBeInteger {
            get {
                return ResourceManager.GetString("StreetcodeAudioIdMustBeInteger", resourceCulture);
            }
        }
        
        internal static string StreetcodeTitleCannotBeEmpty {
            get {
                return ResourceManager.GetString("StreetcodeTitleCannotBeEmpty", resourceCulture);
            }
        }
        
        internal static string StreetcodeTransliterationUrlCannotBeEmpty {
            get {
                return ResourceManager.GetString("StreetcodeTransliterationUrlCannotBeEmpty", resourceCulture);
            }
        }
        
        internal static string StreetcodeTitleTooLong {
            get {
                return ResourceManager.GetString("StreetcodeTitleTooLong", resourceCulture);
            }
        }
        
        internal static string StreetcodeAliasTooLong {
            get {
                return ResourceManager.GetString("StreetcodeAliasTooLong", resourceCulture);
            }
        }
        
        internal static string StreetcodeShortDescriptionTooLong {
            get {
                return ResourceManager.GetString("StreetcodeShortDescriptionTooLong", resourceCulture);
            }
        }
        
        internal static string StreetcodeDateStringTooLong {
            get {
                return ResourceManager.GetString("StreetcodeDateStringTooLong", resourceCulture);
            }
        }
        
        internal static string StreetcodeTeaserTooLong {
            get {
                return ResourceManager.GetString("StreetcodeTeaserTooLong", resourceCulture);
            }
        }
        
        internal static string StreetcodeTransliterationUrlTooLong {
            get {
                return ResourceManager.GetString("StreetcodeTransliterationUrlTooLong", resourceCulture);
            }
        }
        
        internal static string StreetcodeDateRangeInvalid {
            get {
                return ResourceManager.GetString("StreetcodeDateRangeInvalid", resourceCulture);
            }
        }
        
        internal static string StreetcodeAudioIdMustBePositive {
            get {
                return ResourceManager.GetString("StreetcodeAudioIdMustBePositive", resourceCulture);
            }
        }
        
        internal static string AudioNotFound {
            get {
                return ResourceManager.GetString("AudioNotFound", resourceCulture);
            }
        }
        
        internal static string TagNotFoundById {
            get {
                return ResourceManager.GetString("TagNotFoundById", resourceCulture);
            }
        }
        
        internal static string StreetcodeWithIndexAlreadyExists {
            get {
                return ResourceManager.GetString("StreetcodeWithIndexAlreadyExists", resourceCulture);
            }
        }
        
        internal static string StreetcodeNotFoundByCategoryId {
            get {
                return ResourceManager.GetString("StreetcodeNotFoundByCategoryId", resourceCulture);
            }
        }
        
        internal static string StreetcodeFullDeletionFailed {
            get {
                return ResourceManager.GetString("StreetcodeFullDeletionFailed", resourceCulture);
            }
        }
        
        internal static string StreetcodeSoftDeletionFailed {
            get {
                return ResourceManager.GetString("StreetcodeSoftDeletionFailed", resourceCulture);
            }
        }
        
        internal static string SubtitlesNotFound {
            get {
                return ResourceManager.GetString("SubtitlesNotFound", resourceCulture);
            }
        }
        
        internal static string StreetcodeNotFound {
            get {
                return ResourceManager.GetString("StreetcodeNotFound", resourceCulture);
            }
        }
        
        internal static string StreetcodeNotFoundByIndex {
            get {
                return ResourceManager.GetString("StreetcodeNotFoundByIndex", resourceCulture);
            }
        }
        
        internal static string StreetcodeNotFoundByTransliterationUrl {
            get {
                return ResourceManager.GetString("StreetcodeNotFoundByTransliterationUrl", resourceCulture);
            }
        }
        
        internal static string StreetcodeMappingToShortDtoFailed {
            get {
                return ResourceManager.GetString("StreetcodeMappingToShortDtoFailed", resourceCulture);
            }
        }
        
        internal static string StreetcodeIdRequired {
            get {
                return ResourceManager.GetString("StreetcodeIdRequired", resourceCulture);
            }
        }
        
        internal static string StreetcodeIdMustBeInteger {
            get {
                return ResourceManager.GetString("StreetcodeIdMustBeInteger", resourceCulture);
            }
        }
        
        internal static string StreetcodeTypeCannotBeChanged {
            get {
                return ResourceManager.GetString("StreetcodeTypeCannotBeChanged", resourceCulture);
            }
        }
        
        internal static string StreetcodeUpdateExceptionOccurred {
            get {
                return ResourceManager.GetString("StreetcodeUpdateExceptionOccurred", resourceCulture);
            }
        }
        
        internal static string StreetcodeAudioIdInvalid {
            get {
                return ResourceManager.GetString("StreetcodeAudioIdInvalid", resourceCulture);
            }
        }
        
        internal static string StreetcodeAudioNotFound {
            get {
                return ResourceManager.GetString("StreetcodeAudioNotFound", resourceCulture);
            }
        }
        
        internal static string StreetcodeImageNotFoundById {
            get {
                return ResourceManager.GetString("StreetcodeImageNotFoundById", resourceCulture);
            }
        }
        
        internal static string StreetcodeTagNotFoundById {
            get {
                return ResourceManager.GetString("StreetcodeTagNotFoundById", resourceCulture);
            }
        }
        
        internal static string TermNotFound {
            get {
                return ResourceManager.GetString("TermNotFound", resourceCulture);
            }
        }
        
        internal static string TermNotFoundById {
            get {
                return ResourceManager.GetString("TermNotFoundById", resourceCulture);
            }
        }
        
        internal static string TextDataRequired {
            get {
                return ResourceManager.GetString("TextDataRequired", resourceCulture);
            }
        }
        
        internal static string CannotSaveChangesInDatabase {
            get {
                return ResourceManager.GetString("CannotSaveChangesInDatabase", resourceCulture);
            }
        }
        
        internal static string TextIdMustBeGreaterThanZero {
            get {
                return ResourceManager.GetString("TextIdMustBeGreaterThanZero", resourceCulture);
            }
        }
        
        internal static string TextNotFoundById {
            get {
                return ResourceManager.GetString("TextNotFoundById", resourceCulture);
            }
        }
        
        internal static string TextNotFound {
            get {
                return ResourceManager.GetString("TextNotFound", resourceCulture);
            }
        }
        
        internal static string TextParsingFailed {
            get {
                return ResourceManager.GetString("TextParsingFailed", resourceCulture);
            }
        }
        
        internal static string TransactionLinkNotFoundByStreetcodeId {
            get {
                return ResourceManager.GetString("TransactionLinkNotFoundByStreetcodeId", resourceCulture);
            }
        }
        
        internal static string TextTitleRequired {
            get {
                return ResourceManager.GetString("TextTitleRequired", resourceCulture);
            }
        }
        
        internal static string TextTitleTooLong {
            get {
                return ResourceManager.GetString("TextTitleTooLong", resourceCulture);
            }
        }
        
        internal static string TextContentRequired {
            get {
                return ResourceManager.GetString("TextContentRequired", resourceCulture);
            }
        }
        
        internal static string TextContentTooLong {
            get {
                return ResourceManager.GetString("TextContentTooLong", resourceCulture);
            }
        }
        
        internal static string TextAdditionalTextTooLong {
            get {
                return ResourceManager.GetString("TextAdditionalTextTooLong", resourceCulture);
            }
        }
        
        internal static string TextVideoMustBeYouTube {
            get {
                return ResourceManager.GetString("TextVideoMustBeYouTube", resourceCulture);
            }
        }
        
        internal static string TeamNotFound {
            get {
                return ResourceManager.GetString("TeamNotFound", resourceCulture);
            }
        }
        
        internal static string TeamNotFoundById {
            get {
                return ResourceManager.GetString("TeamNotFoundById", resourceCulture);
            }
        }
        
        internal static string PositionNameRequired {
            get {
                return ResourceManager.GetString("PositionNameRequired", resourceCulture);
            }
        }
        
        internal static string PositionNameTooLong {
            get {
                return ResourceManager.GetString("PositionNameTooLong", resourceCulture);
            }
        }
        
        internal static string PositionsNotFound {
            get {
                return ResourceManager.GetString("PositionsNotFound", resourceCulture);
            }
        }
        
        internal static string TeamMemberLinkDataRequired {
            get {
                return ResourceManager.GetString("TeamMemberLinkDataRequired", resourceCulture);
            }
        }
        
        internal static string TeamCreationFailed {
            get {
                return ResourceManager.GetString("TeamCreationFailed", resourceCulture);
            }
        }
        
        internal static string TeamLinkCreationFailed {
            get {
                return ResourceManager.GetString("TeamLinkCreationFailed", resourceCulture);
            }
        }
        
        internal static string TeamMemberLinkConversionFailed {
            get {
                return ResourceManager.GetString("TeamMemberLinkConversionFailed", resourceCulture);
            }
        }
        
        internal static string TeamMemberLinkLogoTypeRequired {
            get {
                return ResourceManager.GetString("TeamMemberLinkLogoTypeRequired", resourceCulture);
            }
        }
        
        internal static string TeamMemberLinkTargetUrlRequired {
            get {
                return ResourceManager.GetString("TeamMemberLinkTargetUrlRequired", resourceCulture);
            }
        }
        
        internal static string TeamMemberLinkTargetUrlInvalid {
            get {
                return ResourceManager.GetString("TeamMemberLinkTargetUrlInvalid", resourceCulture);
            }
        }
        
        internal static string TeamMemberIdMustBeGreaterThanZero {
            get {
                return ResourceManager.GetString("TeamMemberIdMustBeGreaterThanZero", resourceCulture);
            }
        }
        
        internal static string TeamMemberLinkNotFound {
            get {
                return ResourceManager.GetString("TeamMemberLinkNotFound", resourceCulture);
            }
        }
        
        internal static string HistoricalContextNotFound {
            get {
                return ResourceManager.GetString("HistoricalContextNotFound", resourceCulture);
            }
        }
        
        internal static string TimelineItemNotFound {
            get {
                return ResourceManager.GetString("TimelineItemNotFound", resourceCulture);
            }
        }
        
        internal static string TimelineItemNotFoundByStreetcodeId {
            get {
                return ResourceManager.GetString("TimelineItemNotFoundByStreetcodeId", resourceCulture);
            }
        }
        
        internal static string TimelineItemNotFoundById {
            get {
                return ResourceManager.GetString("TimelineItemNotFoundById", resourceCulture);
            }
        }
        
        internal static string ToponymNotFoundById {
            get {
                return ResourceManager.GetString("ToponymNotFoundById", resourceCulture);
            }
        }
        
        internal static string ToponymNotFoundByStreetcodeId {
            get {
                return ResourceManager.GetString("ToponymNotFoundByStreetcodeId", resourceCulture);
            }
        }
        
        internal static string TransactionLinkNotFound {
            get {
                return ResourceManager.GetString("TransactionLinkNotFound", resourceCulture);
            }
        }
        
        internal static string TransactionLinkNotFoundById {
            get {
                return ResourceManager.GetString("TransactionLinkNotFoundById", resourceCulture);
            }
        }
        
        internal static string UserDataRequired {
            get {
                return ResourceManager.GetString("UserDataRequired", resourceCulture);
            }
        }
        
        internal static string UserNameRequired {
            get {
                return ResourceManager.GetString("UserNameRequired", resourceCulture);
            }
        }
        
        internal static string UserNameTooLong {
            get {
                return ResourceManager.GetString("UserNameTooLong", resourceCulture);
            }
        }
        
        internal static string UserSurnameTooLong {
            get {
                return ResourceManager.GetString("UserSurnameTooLong", resourceCulture);
            }
        }
        
        internal static string UserLoginRequired {
            get {
                return ResourceManager.GetString("UserLoginRequired", resourceCulture);
            }
        }
        
        internal static string UserLoginTooLong {
            get {
                return ResourceManager.GetString("UserLoginTooLong", resourceCulture);
            }
        }
        
        internal static string UserLoginInvalidFormat {
            get {
                return ResourceManager.GetString("UserLoginInvalidFormat", resourceCulture);
            }
        }
        
        internal static string UserEmailRequired {
            get {
                return ResourceManager.GetString("UserEmailRequired", resourceCulture);
            }
        }
        
        internal static string UserEmailInvalidFormat {
            get {
                return ResourceManager.GetString("UserEmailInvalidFormat", resourceCulture);
            }
        }
        
        internal static string UserEmailTooLong {
            get {
                return ResourceManager.GetString("UserEmailTooLong", resourceCulture);
            }
        }
        
        internal static string UserPasswordRequired {
            get {
                return ResourceManager.GetString("UserPasswordRequired", resourceCulture);
            }
        }
        
        internal static string UserPasswordTooShort {
            get {
                return ResourceManager.GetString("UserPasswordTooShort", resourceCulture);
            }
        }
        
        internal static string UserPasswordTooLong {
            get {
                return ResourceManager.GetString("UserPasswordTooLong", resourceCulture);
            }
        }
        
        internal static string UserPasswordInvalidFormat {
            get {
                return ResourceManager.GetString("UserPasswordInvalidFormat", resourceCulture);
            }
        }
        
        internal static string UserRoleInvalid {
            get {
                return ResourceManager.GetString("UserRoleInvalid", resourceCulture);
            }
        }
        
        internal static string UserPhoneNumberInvalidFormat {
            get {
                return ResourceManager.GetString("UserPhoneNumberInvalidFormat", resourceCulture);
            }
        }
        
        internal static string UserAlreadyExists {
            get {
                return ResourceManager.GetString("UserAlreadyExists", resourceCulture);
            }
        }
        
        internal static string UserRoleAssignmentFailed {
            get {
                return ResourceManager.GetString("UserRoleAssignmentFailed", resourceCulture);
            }
        }
        
        internal static string UserEmailOrPasswordInvalid {
            get {
                return ResourceManager.GetString("UserEmailOrPasswordInvalid", resourceCulture);
            }
        }
    }
}
