//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Streetcode.BLL {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ErrorMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMessages() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Streetcode.BLL.ErrorMessages", typeof(ErrorMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Alt текст не може перевищувати {0} символів.
        /// </summary>
        internal static string AltTextTooLong {
            get {
                return ResourceManager.GetString("AltTextTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cannot find an art with corresponding id: {0}.
        /// </summary>
        internal static string ArtNotFoundById {
            get {
                return ResourceManager.GetString("ArtNotFoundById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cannot find any art with corresponding streetcode id: {0}.
        /// </summary>
        internal static string ArtNotFoundByStreetcodeId {
            get {
                return ResourceManager.GetString("ArtNotFoundByStreetcodeId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cannot find any arts.
        /// </summary>
        internal static string ArtsNotFound {
            get {
                return ResourceManager.GetString("ArtsNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на BaseFormat має бути дійсним рядком Base64.
        /// </summary>
        internal static string AudioBase64Invalid {
            get {
                return ResourceManager.GetString("AudioBase64Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Дані аудіо в Base64 є обов&apos;язковими.
        /// </summary>
        internal static string AudioBase64Required {
            get {
                return ResourceManager.GetString("AudioBase64Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Failed to create an audio.
        /// </summary>
        internal static string AudioCreationFailed {
            get {
                return ResourceManager.GetString("AudioCreationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Дані аудіо є обов&apos;язковими.
        /// </summary>
        internal static string AudioDataRequired {
            get {
                return ResourceManager.GetString("AudioDataRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Failed to delete an audio.
        /// </summary>
        internal static string AudioDeletionFailed {
            get {
                return ResourceManager.GetString("AudioDeletionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Розширення аудіо має бути одним з: {0}.
        /// </summary>
        internal static string AudioExtensionInvalid {
            get {
                return ResourceManager.GetString("AudioExtensionInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Розширення аудіо є обов&apos;язковим.
        /// </summary>
        internal static string AudioExtensionRequired {
            get {
                return ResourceManager.GetString("AudioExtensionRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Audio not found.
        /// </summary>
        internal static string AudioNotFound {
            get {
                return ResourceManager.GetString("AudioNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cannot find an audio with corresponding audioId: {0}.
        /// </summary>
        internal static string AudioNotFoundById {
            get {
                return ResourceManager.GetString("AudioNotFoundById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cannot find an audio with the corresponding streetcode id: {0}.
        /// </summary>
        internal static string AudioNotFoundByStreetcodeId {
            get {
                return ResourceManager.GetString("AudioNotFoundByStreetcodeId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Розмір аудіо не може перевищувати {0}МБ після декодування.
        /// </summary>
        internal static string AudioSizeExceeded {
            get {
                return ResourceManager.GetString("AudioSizeExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cannot find any audios.
        /// </summary>
        internal static string AudiosNotFound {
            get {
                return ResourceManager.GetString("AudiosNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cannot create new related word for a term!.
        /// </summary>
        internal static string CannotCreateRelatedWordForTerm {
            get {
                return ResourceManager.GetString("CannotCreateRelatedWordForTerm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cannot map entity.
        /// </summary>
        internal static string CannotMapEntity {
            get {
                return ResourceManager.GetString("CannotMapEntity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cannot save changes in the database..
        /// </summary>
        internal static string CannotSaveChangesInDatabase {
            get {
                return ResourceManager.GetString("CannotSaveChangesInDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cannot save changes in the database after related word creation!.
        /// </summary>
        internal static string CannotSaveChangesInDbAfterStreetcodeCreated {
            get {
                return ResourceManager.GetString("CannotSaveChangesInDbAfterStreetcodeCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Categories is null.
        /// </summary>
        internal static string CategoriesNotFound {
            get {
                return ResourceManager.GetString("CategoriesNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cannot find any srcCategory by the corresponding id: {0}.
        /// </summary>
        internal static string CategoryNotFoundById {
            get {
                return ResourceManager.GetString("CategoryNotFoundById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cant find any source category with the streetcode id {0}.
        /// </summary>
        internal static string CategoryNotFoundByStreetcodeId {
            get {
                return ResourceManager.GetString("CategoryNotFoundByStreetcodeId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Дані координат не можуть бути порожніми.
        /// </summary>
        internal static string CoordinateCantBeEmpty {
            get {
                return ResourceManager.GetString("CoordinateCantBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Довгота має бути в межах від {0} до {1} градусів.
        /// </summary>
        internal static string CoordinateHeightError {
            get {
                return ResourceManager.GetString("CoordinateHeightError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ID координат має бути більше 0.
        /// </summary>
        internal static string CoordinateIdMustBeGreaterThanZero {
            get {
                return ResourceManager.GetString("CoordinateIdMustBeGreaterThanZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Широта має бути в межах від {0} до {1} градусів.
        /// </summary>
        internal static string CoordinateWidthError {
            get {
                return ResourceManager.GetString("CoordinateWidthError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Database connection failed.
        /// </summary>
        internal static string DatabaseConntectionFailed {
            get {
                return ResourceManager.GetString("DatabaseConntectionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Database error occurred.
        /// </summary>
        internal static string DataBaseError {
            get {
                return ResourceManager.GetString("DataBaseError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Database error occurred.
        /// </summary>
        internal static string DatabaseErrorOccured {
            get {
                return ResourceManager.GetString("DatabaseErrorOccured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Delete verification not implemented for type {0}.
        /// </summary>
        internal static string DeleteVerificationWrongType {
            get {
                return ResourceManager.GetString("DeleteVerificationWrongType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Опис не може перевищувати {0} символів.
        /// </summary>
        internal static string DescriptionTooLong {
            get {
                return ResourceManager.GetString("DescriptionTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Зміст факту є обов&apos;язковим.
        /// </summary>
        internal static string FactContentRequired {
            get {
                return ResourceManager.GetString("FactContentRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Зміст факту не може перевищувати {0} символів.
        /// </summary>
        internal static string FactContentTooLong {
            get {
                return ResourceManager.GetString("FactContentTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Дані факту не можуть бути порожніми.
        /// </summary>
        internal static string FactDataRequired {
            get {
                return ResourceManager.GetString("FactDataRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ID факту має бути більше 0.
        /// </summary>
        internal static string FactIdMustBeGreaterThanZero {
            get {
                return ResourceManager.GetString("FactIdMustBeGreaterThanZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ID зображення має бути більше 0.
        /// </summary>
        internal static string FactImageIdMustBeGreaterThanZero {
            get {
                return ResourceManager.GetString("FactImageIdMustBeGreaterThanZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Failed to map CreateFactDTO to Fact entity.
        /// </summary>
        internal static string FactMappingFailed {
            get {
                return ResourceManager.GetString("FactMappingFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Fact was not found.
        /// </summary>
        internal static string FactNotFound {
            get {
                return ResourceManager.GetString("FactNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cannot find any fact with corresponding id: {0}.
        /// </summary>
        internal static string FactNotFoundById {
            get {
                return ResourceManager.GetString("FactNotFoundById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cannot find any fact by the streetcode id:.
        /// </summary>
        internal static string FactNotFoundByStreetcodeId {
            get {
                return ResourceManager.GetString("FactNotFoundByStreetcodeId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Fact with the same title already exists for this Streetcode.
        /// </summary>
        internal static string FactTitleAlreadyExists {
            get {
                return ResourceManager.GetString("FactTitleAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Заголовок факту є обов&apos;язковим.
        /// </summary>
        internal static string FactTitleRequired {
            get {
                return ResourceManager.GetString("FactTitleRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Заголовок факту не може перевищувати {0} символів.
        /// </summary>
        internal static string FactTitleTooLong {
            get {
                return ResourceManager.GetString("FactTitleTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Failed to delete streetcode-toponym relationship..
        /// </summary>
        internal static string FailedToDeleteToponymStreetcode {
            get {
                return ResourceManager.GetString("FailedToDeleteToponymStreetcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Failed to merge toponyms.
        /// </summary>
        internal static string FailedToMergeToponyms {
            get {
                return ResourceManager.GetString("FailedToMergeToponyms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cannot find any historical contexts.
        /// </summary>
        internal static string HistoricalContextNotFound {
            get {
                return ResourceManager.GetString("HistoricalContextNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Id має бути більше 0.
        /// </summary>
        internal static string IdMustBeGreaterThan {
            get {
                return ResourceManager.GetString("IdMustBeGreaterThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на BaseFormat має бути дійсним рядком Base64.
        /// </summary>
        internal static string ImageBase64Invalid {
            get {
                return ResourceManager.GetString("ImageBase64Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Дані зображення в Base64 є обов&apos;язковими.
        /// </summary>
        internal static string ImageBase64Required {
            get {
                return ResourceManager.GetString("ImageBase64Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Failed to create an image.
        /// </summary>
        internal static string ImageCreationFailed {
            get {
                return ResourceManager.GetString("ImageCreationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Дані зображення є обов&apos;язковими.
        /// </summary>
        internal static string ImageDataRequired {
            get {
                return ResourceManager.GetString("ImageDataRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Failed to delete an image.
        /// </summary>
        internal static string ImageDeletionFailed {
            get {
                return ResourceManager.GetString("ImageDeletionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Розширення зображення має бути одним з: {0}.
        /// </summary>
        internal static string ImageExtensionInvalid {
            get {
                return ResourceManager.GetString("ImageExtensionInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Розширення зображення є обов&apos;язковим.
        /// </summary>
        internal static string ImageExtensionRequired {
            get {
                return ResourceManager.GetString("ImageExtensionRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ID зображення має бути більше 0.
        /// </summary>
        internal static string ImageIdMustBeGreaterThanZero {
            get {
                return ResourceManager.GetString("ImageIdMustBeGreaterThanZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cannot find any image.
        /// </summary>
        internal static string ImageNotFound {
            get {
                return ResourceManager.GetString("ImageNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cannot find an image with corresponding categoryId: {0}.
        /// </summary>
        internal static string ImageNotFoundByCategoryId {
            get {
                return ResourceManager.GetString("ImageNotFoundByCategoryId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cannot find an image with corresponding id: {0}.
        /// </summary>
        internal static string ImageNotFoundById {
            get {
                return ResourceManager.GetString("ImageNotFoundById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cannot find an image with the corresponding streetcode id:.
        /// </summary>
        internal static string ImageNotFoundByStreetcodeId {
            get {
                return ResourceManager.GetString("ImageNotFoundByStreetcodeId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Розмір зображення не може перевищувати {0}МБ після декодування.
        /// </summary>
        internal static string ImageSizeExceeded {
            get {
                return ResourceManager.GetString("ImageSizeExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на because include expression should be provided.
        /// </summary>
        internal static string IncludeExpressionNotProvided {
            get {
                return ResourceManager.GetString("IncludeExpressionNotProvided", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Invalid image format. Allowed formats: .png, .jpg, .jpeg, .webp.
        /// </summary>
        internal static string InvalidImageFormat {
            get {
                return ResourceManager.GetString("InvalidImageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Map method to {0} should not be called at all.
        /// </summary>
        internal static string MapToExatct {
            get {
                return ResourceManager.GetString("MapToExatct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на MimeType не може перевищувати {0} символів.
        /// </summary>
        internal static string MimeTypeTooLong {
            get {
                return ResourceManager.GetString("MimeTypeTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cannot convert null to news.
        /// </summary>
        internal static string NewsConversionFailed {
            get {
                return ResourceManager.GetString("NewsConversionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Дата створення не може бути в майбутньому.
        /// </summary>
        internal static string NewsCreationDateInFuture {
            get {
                return ResourceManager.GetString("NewsCreationDateInFuture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Дата створення є обов&apos;язковою.
        /// </summary>
        internal static string NewsCreationDateRequired {
            get {
                return ResourceManager.GetString("NewsCreationDateRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Failed to create a news.
        /// </summary>
        internal static string NewsCreationFailed {
            get {
                return ResourceManager.GetString("NewsCreationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Дані новини є обов&apos;язковими.
        /// </summary>
        internal static string NewsDataRequired {
            get {
                return ResourceManager.GetString("NewsDataRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Failed to delete news.
        /// </summary>
        internal static string NewsDeletionFailed {
            get {
                return ResourceManager.GetString("NewsDeletionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Id новини має бути більше 0.
        /// </summary>
        internal static string NewsIdMustBeGreaterThanZero {
            get {
                return ResourceManager.GetString("NewsIdMustBeGreaterThanZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на There are no news in the database.
        /// </summary>
        internal static string NewsNotFound {
            get {
                return ResourceManager.GetString("NewsNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на No news found by entered Id - {0}.
        /// </summary>
        internal static string NewsNotFoundById {
            get {
                return ResourceManager.GetString("NewsNotFoundById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на No news by entered Url - {0}.
        /// </summary>
        internal static string NewsNotFoundByUrl {
            get {
                return ResourceManager.GetString("NewsNotFoundByUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Текст новини є обов&apos;язковим.
        /// </summary>
        internal static string NewsTextRequired {
            get {
                return ResourceManager.GetString("NewsTextRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Назва новини є обов&apos;язковою.
        /// </summary>
        internal static string NewsTitleRequired {
            get {
                return ResourceManager.GetString("NewsTitleRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Назва новини не може перевищувати {0} символів.
        /// </summary>
        internal static string NewsTitleTooLong {
            get {
                return ResourceManager.GetString("NewsTitleTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Failed to update news.
        /// </summary>
        internal static string NewsUpdateFailed {
            get {
                return ResourceManager.GetString("NewsUpdateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на URL новини є обов&apos;язковим.
        /// </summary>
        internal static string NewsUrlRequired {
            get {
                return ResourceManager.GetString("NewsUrlRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на URL новини не може перевищувати {0} символів.
        /// </summary>
        internal static string NewsUrlTooLong {
            get {
                return ResourceManager.GetString("NewsUrlTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на because predicate should be provided for filtering streetcodes.
        /// </summary>
        internal static string NoPredicateProvidedForFilterStreetcode {
            get {
                return ResourceManager.GetString("NoPredicateProvidedForFilterStreetcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Request is null.
        /// </summary>
        internal static string NullRequest {
            get {
                return ResourceManager.GetString("NullRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Дані партнера є обов&apos;язковими.
        /// </summary>
        internal static string PartnerDataRequired {
            get {
                return ResourceManager.GetString("PartnerDataRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Опис не може перевищувати {0} символів.
        /// </summary>
        internal static string PartnerDescriptionTooLong {
            get {
                return ResourceManager.GetString("PartnerDescriptionTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ID партнера має бути більше 0.
        /// </summary>
        internal static string PartnerIdMustBeGreaterThanZero {
            get {
                return ResourceManager.GetString("PartnerIdMustBeGreaterThanZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на LogoId має бути більше 0.
        /// </summary>
        internal static string PartnerLogoIdMustBeGreaterThanZero {
            get {
                return ResourceManager.GetString("PartnerLogoIdMustBeGreaterThanZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на No partner with such id.
        /// </summary>
        internal static string PartnerNotFound {
            get {
                return ResourceManager.GetString("PartnerNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cannot find any partner with corresponding id: {0}.
        /// </summary>
        internal static string PartnerNotFoundById {
            get {
                return ResourceManager.GetString("PartnerNotFoundById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cannot find any partners.
        /// </summary>
        internal static string PartnersNotFound {
            get {
                return ResourceManager.GetString("PartnersNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cannot find any partner with corresponding streetcode id: {0}.
        /// </summary>
        internal static string PartnersNotFoundByStreetcodeId {
            get {
                return ResourceManager.GetString("PartnersNotFoundByStreetcodeId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Список стріткодів є обов&apos;язковим.
        /// </summary>
        internal static string PartnerStreetcodesRequired {
            get {
                return ResourceManager.GetString("PartnerStreetcodesRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на TargetUrl має бути дійсною абсолютною URL-адресою.
        /// </summary>
        internal static string PartnerTargetUrlInvalid {
            get {
                return ResourceManager.GetString("PartnerTargetUrlInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Партнер з такою назвою вже існує.
        /// </summary>
        internal static string PartnerTitleAlreadyExists {
            get {
                return ResourceManager.GetString("PartnerTitleAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Назва партнера є обов&apos;язковою.
        /// </summary>
        internal static string PartnerTitleRequired {
            get {
                return ResourceManager.GetString("PartnerTitleRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Назва партнера не може перевищувати {0} символів.
        /// </summary>
        internal static string PartnerTitleTooLong {
            get {
                return ResourceManager.GetString("PartnerTitleTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на UrlTitle не може перевищувати {0} символів.
        /// </summary>
        internal static string PartnerUrlTitleTooLong {
            get {
                return ResourceManager.GetString("PartnerUrlTitleTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сума платежу не може перевищувати {0:N0}.
        /// </summary>
        internal static string PaymentAmountExceeded {
            get {
                return ResourceManager.GetString("PaymentAmountExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сума платежу має бути більше 0.
        /// </summary>
        internal static string PaymentAmountMustBeGreaterThanZero {
            get {
                return ResourceManager.GetString("PaymentAmountMustBeGreaterThanZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Дані платежу не можуть бути порожніми.
        /// </summary>
        internal static string PaymentDataRequired {
            get {
                return ResourceManager.GetString("PaymentDataRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на URL перенаправлення має бути правильним.
        /// </summary>
        internal static string PaymentRedirectUrlInvalid {
            get {
                return ResourceManager.GetString("PaymentRedirectUrlInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на URL перенаправлення не може перевищувати {0} символів.
        /// </summary>
        internal static string PaymentRedirectUrlTooLong {
            get {
                return ResourceManager.GetString("PaymentRedirectUrlTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Назва посади є обов&apos;язковою.
        /// </summary>
        internal static string PositionNameRequired {
            get {
                return ResourceManager.GetString("PositionNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Назва посади не може перевищувати {0} символів.
        /// </summary>
        internal static string PositionNameTooLong {
            get {
                return ResourceManager.GetString("PositionNameTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cannot find any positions.
        /// </summary>
        internal static string PositionsNotFound {
            get {
                return ResourceManager.GetString("PositionsNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на because predicate should be provided.
        /// </summary>
        internal static string PredicateNotProvided {
            get {
                return ResourceManager.GetString("PredicateNotProvided", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Failed to create a relation.
        /// </summary>
        internal static string RelatedFigureCreationFailed {
            get {
                return ResourceManager.GetString("RelatedFigureCreationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Failed to delete a relation.
        /// </summary>
        internal static string RelatedFigureDeletionFailed {
            get {
                return ResourceManager.GetString("RelatedFigureDeletionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cannot find a relation between streetcodes with corresponding ids: {0} &amp; &apos;{1}&apos;.
        /// </summary>
        internal static string RelatedFigureNotFound {
            get {
                return ResourceManager.GetString("RelatedFigureNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ID стріткоду-спостерігача має бути більше 0.
        /// </summary>
        internal static string RelatedFigureObserverIdMustBeGreaterThanZero {
            get {
                return ResourceManager.GetString("RelatedFigureObserverIdMustBeGreaterThanZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Стріткод не може бути пов&apos;язаний сам з собою.
        /// </summary>
        internal static string RelatedFigureSelfReferenceNotAllowed {
            get {
                return ResourceManager.GetString("RelatedFigureSelfReferenceNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ID цільового стріткоду має бути більше 0.
        /// </summary>
        internal static string RelatedFigureTargetIdMustBeGreaterThanZero {
            get {
                return ResourceManager.GetString("RelatedFigureTargetIdMustBeGreaterThanZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Дані пов&apos;язаного терміну не можуть бути порожніми.
        /// </summary>
        internal static string RelatedTermDataRequired {
            get {
                return ResourceManager.GetString("RelatedTermDataRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Failed to delete a related term.
        /// </summary>
        internal static string RelatedTermDeletionFailed {
            get {
                return ResourceManager.GetString("RelatedTermDeletionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ID терміну має бути більше 0.
        /// </summary>
        internal static string RelatedTermIdMustBeGreaterThanZero {
            get {
                return ResourceManager.GetString("RelatedTermIdMustBeGreaterThanZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cannot find a related term: {0}.
        /// </summary>
        internal static string RelatedTermNotFound {
            get {
                return ResourceManager.GetString("RelatedTermNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cannot create DTOs for related words.
        /// </summary>
        internal static string RelatedTermsMappingFailed {
            get {
                return ResourceManager.GetString("RelatedTermsMappingFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cannot get words by term id.
        /// </summary>
        internal static string RelatedTermsNotFoundByTermId {
            get {
                return ResourceManager.GetString("RelatedTermsNotFoundByTermId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Слово з цим визначенням уже існує.
        /// </summary>
        internal static string RelatedTermWordAlreadyExists {
            get {
                return ResourceManager.GetString("RelatedTermWordAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Слово для видалення є обов&apos;язковим.
        /// </summary>
        internal static string RelatedTermWordForDeletionRequired {
            get {
                return ResourceManager.GetString("RelatedTermWordForDeletionRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Слово є обов&apos;язковим.
        /// </summary>
        internal static string RelatedTermWordRequired {
            get {
                return ResourceManager.GetString("RelatedTermWordRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Слово не може перевищувати {0} символів.
        /// </summary>
        internal static string RelatedTermWordTooLong {
            get {
                return ResourceManager.GetString("RelatedTermWordTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Alias не може перевищувати {0} символів.
        /// </summary>
        internal static string StreetcodeAliasTooLong {
            get {
                return ResourceManager.GetString("StreetcodeAliasTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Invalid audio Id.
        /// </summary>
        internal static string StreetcodeAudioIdInvalid {
            get {
                return ResourceManager.GetString("StreetcodeAudioIdInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на AudioId має бути цілим числом.
        /// </summary>
        internal static string StreetcodeAudioIdMustBeInteger {
            get {
                return ResourceManager.GetString("StreetcodeAudioIdMustBeInteger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на AudioId має бути більше {0}.
        /// </summary>
        internal static string StreetcodeAudioIdMustBePositive {
            get {
                return ResourceManager.GetString("StreetcodeAudioIdMustBePositive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Audio doesn&apos;t exist.
        /// </summary>
        internal static string StreetcodeAudioNotFound {
            get {
                return ResourceManager.GetString("StreetcodeAudioNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Failed to create a streetcode.
        /// </summary>
        internal static string StreetcodeCreationFailed {
            get {
                return ResourceManager.GetString("StreetcodeCreationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Дані стріткоду є обов&apos;язковими.
        /// </summary>
        internal static string StreetcodeDataRequired {
            get {
                return ResourceManager.GetString("StreetcodeDataRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на EventEndOrPersonDeathDate має бути пізніше ніж EventStartOrPersonBirthDate.
        /// </summary>
        internal static string StreetcodeDateRangeInvalid {
            get {
                return ResourceManager.GetString("StreetcodeDateRangeInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на DateString не може перевищувати {0} символів.
        /// </summary>
        internal static string StreetcodeDateStringTooLong {
            get {
                return ResourceManager.GetString("StreetcodeDateStringTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на EventEndOrPersonDeathDate має бути дійсною датою.
        /// </summary>
        internal static string StreetcodeEventEndOrPersonDeathDateInvalid {
            get {
                return ResourceManager.GetString("StreetcodeEventEndOrPersonDeathDateInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на EventStartOrPersonBirthDate має бути дійсною датою.
        /// </summary>
        internal static string StreetcodeEventStartOrPersonBirthDateInvalid {
            get {
                return ResourceManager.GetString("StreetcodeEventStartOrPersonBirthDateInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на EventStartOrPersonBirthDate є обов&apos;язковим.
        /// </summary>
        internal static string StreetcodeEventStartOrPersonBirthDateRequired {
            get {
                return ResourceManager.GetString("StreetcodeEventStartOrPersonBirthDateRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Failed to delete streetcode fully.
        /// </summary>
        internal static string StreetcodeFullDeletionFailed {
            get {
                return ResourceManager.GetString("StreetcodeFullDeletionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ID стріткоду має бути більше 0.
        /// </summary>
        internal static string StreetcodeIdMustBeGreaterThanZero {
            get {
                return ResourceManager.GetString("StreetcodeIdMustBeGreaterThanZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Id має бути цілим числом.
        /// </summary>
        internal static string StreetcodeIdMustBeInteger {
            get {
                return ResourceManager.GetString("StreetcodeIdMustBeInteger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Id є обов&apos;язковим.
        /// </summary>
        internal static string StreetcodeIdRequired {
            get {
                return ResourceManager.GetString("StreetcodeIdRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Image {0} not found.
        /// </summary>
        internal static string StreetcodeImageNotFoundById {
            get {
                return ResourceManager.GetString("StreetcodeImageNotFoundById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Index має бути цілим числом.
        /// </summary>
        internal static string StreetcodeIndexMustBeInteger {
            get {
                return ResourceManager.GetString("StreetcodeIndexMustBeInteger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Index є обов&apos;язковим.
        /// </summary>
        internal static string StreetcodeIndexRequired {
            get {
                return ResourceManager.GetString("StreetcodeIndexRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cannot map streetcode to shortDTO.
        /// </summary>
        internal static string StreetcodeMappingToShortDtoFailed {
            get {
                return ResourceManager.GetString("StreetcodeMappingToShortDtoFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на No such streetcode exists.
        /// </summary>
        internal static string StreetcodeNotFound {
            get {
                return ResourceManager.GetString("StreetcodeNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cannot find a streetcode with corresponding categoryId: {0}.
        /// </summary>
        internal static string StreetcodeNotFoundByCategoryId {
            get {
                return ResourceManager.GetString("StreetcodeNotFoundByCategoryId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Streetcode with id: {0} doesn&apos;t exist.
        /// </summary>
        internal static string StreetcodeNotFoundById {
            get {
                return ResourceManager.GetString("StreetcodeNotFoundById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Streetcode with index: {0} doesn&apos;t exist.
        /// </summary>
        internal static string StreetcodeNotFoundByIndex {
            get {
                return ResourceManager.GetString("StreetcodeNotFoundByIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cannot find any streetcode with corresponding tagid: {0}.
        /// </summary>
        internal static string StreetcodeNotFoundByTagId {
            get {
                return ResourceManager.GetString("StreetcodeNotFoundByTagId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cannot find streetcode by transliteration url: {0}.
        /// </summary>
        internal static string StreetcodeNotFoundByTransliterationUrl {
            get {
                return ResourceManager.GetString("StreetcodeNotFoundByTransliterationUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Streetcode repository error.
        /// </summary>
        internal static string StreetcodeRepositoryError {
            get {
                return ResourceManager.GetString("StreetcodeRepositoryError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ShortDescription не може перевищувати {0} символів.
        /// </summary>
        internal static string StreetcodeShortDescriptionTooLong {
            get {
                return ResourceManager.GetString("StreetcodeShortDescriptionTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Failed to change status of streetcode to deleted.
        /// </summary>
        internal static string StreetcodeSoftDeletionFailed {
            get {
                return ResourceManager.GetString("StreetcodeSoftDeletionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Tag {0} not found.
        /// </summary>
        internal static string StreetcodeTagNotFoundById {
            get {
                return ResourceManager.GetString("StreetcodeTagNotFoundById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Teaser не може перевищувати {0} символів.
        /// </summary>
        internal static string StreetcodeTeaserTooLong {
            get {
                return ResourceManager.GetString("StreetcodeTeaserTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Exception occurred while creating streetcode: Test exception.
        /// </summary>
        internal static string StreetcodeTestException {
            get {
                return ResourceManager.GetString("StreetcodeTestException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Назва не може бути порожньою.
        /// </summary>
        internal static string StreetcodeTitleCannotBeEmpty {
            get {
                return ResourceManager.GetString("StreetcodeTitleCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Назва є обов&apos;язковою.
        /// </summary>
        internal static string StreetcodeTitleRequired {
            get {
                return ResourceManager.GetString("StreetcodeTitleRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Назва не може перевищувати {0} символів.
        /// </summary>
        internal static string StreetcodeTitleTooLong {
            get {
                return ResourceManager.GetString("StreetcodeTitleTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на TransliterationUrl не може бути порожнім.
        /// </summary>
        internal static string StreetcodeTransliterationUrlCannotBeEmpty {
            get {
                return ResourceManager.GetString("StreetcodeTransliterationUrlCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на TransliterationUrl є обов&apos;язковим.
        /// </summary>
        internal static string StreetcodeTransliterationUrlRequired {
            get {
                return ResourceManager.GetString("StreetcodeTransliterationUrlRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на TransliterationUrl не може перевищувати {0} символів.
        /// </summary>
        internal static string StreetcodeTransliterationUrlTooLong {
            get {
                return ResourceManager.GetString("StreetcodeTransliterationUrlTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на StreetcodeType value can&apos;t be changed.
        /// </summary>
        internal static string StreetcodeTypeCannotBeChanged {
            get {
                return ResourceManager.GetString("StreetcodeTypeCannotBeChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на StreetcodeType має бути одним з: {0}.
        /// </summary>
        internal static string StreetcodeTypeInvalid {
            get {
                return ResourceManager.GetString("StreetcodeTypeInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на StreetcodeType є обов&apos;язковим.
        /// </summary>
        internal static string StreetcodeTypeRequired {
            get {
                return ResourceManager.GetString("StreetcodeTypeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Exception occurred while updating streetcode: {0}.
        /// </summary>
        internal static string StreetcodeUpdateExceptionOccurred {
            get {
                return ResourceManager.GetString("StreetcodeUpdateExceptionOccurred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Streetcode with Index {0} already exists.
        /// </summary>
        internal static string StreetcodeWithIndexAlreadyExists {
            get {
                return ResourceManager.GetString("StreetcodeWithIndexAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cannot find any subtitles.
        /// </summary>
        internal static string SubtitlesNotFound {
            get {
                return ResourceManager.GetString("SubtitlesNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Дані тегу не можуть бути порожніми.
        /// </summary>
        internal static string TagDataCantBeEmpty {
            get {
                return ResourceManager.GetString("TagDataCantBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Назва тегу може містити лише літери, цифри, пробіли та дефіси.
        /// </summary>
        internal static string TagFormatError {
            get {
                return ResourceManager.GetString("TagFormatError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Назва тегу не може перевищувати {0} символів.
        /// </summary>
        internal static string TagNameCantExceed {
            get {
                return ResourceManager.GetString("TagNameCantExceed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Назва тегу є обов&apos;язковою.
        /// </summary>
        internal static string TagNameIsRequired {
            get {
                return ResourceManager.GetString("TagNameIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Tag {0} not found.
        /// </summary>
        internal static string TagNotFoundById {
            get {
                return ResourceManager.GetString("TagNotFoundById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Failed to create a team.
        /// </summary>
        internal static string TeamCreationFailed {
            get {
                return ResourceManager.GetString("TeamCreationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cannot create team link.
        /// </summary>
        internal static string TeamLinkCreationFailed {
            get {
                return ResourceManager.GetString("TeamLinkCreationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на TeamMemberId має бути більше 0.
        /// </summary>
        internal static string TeamMemberIdMustBeGreaterThanZero {
            get {
                return ResourceManager.GetString("TeamMemberIdMustBeGreaterThanZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cannot convert null to team link.
        /// </summary>
        internal static string TeamMemberLinkConversionFailed {
            get {
                return ResourceManager.GetString("TeamMemberLinkConversionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Посилання на члена команди є обов&apos;язковим.
        /// </summary>
        internal static string TeamMemberLinkDataRequired {
            get {
                return ResourceManager.GetString("TeamMemberLinkDataRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на LogoType є обов&apos;язковим.
        /// </summary>
        internal static string TeamMemberLinkLogoTypeRequired {
            get {
                return ResourceManager.GetString("TeamMemberLinkLogoTypeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cannot find any team links.
        /// </summary>
        internal static string TeamMemberLinkNotFound {
            get {
                return ResourceManager.GetString("TeamMemberLinkNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на TargetUrl має бути дійсною URL-адресою.
        /// </summary>
        internal static string TeamMemberLinkTargetUrlInvalid {
            get {
                return ResourceManager.GetString("TeamMemberLinkTargetUrlInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на TargetUrl є обов&apos;язковим.
        /// </summary>
        internal static string TeamMemberLinkTargetUrlRequired {
            get {
                return ResourceManager.GetString("TeamMemberLinkTargetUrlRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cannot find any team.
        /// </summary>
        internal static string TeamNotFound {
            get {
                return ResourceManager.GetString("TeamNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cannot find any team with corresponding id: {0}.
        /// </summary>
        internal static string TeamNotFoundById {
            get {
                return ResourceManager.GetString("TeamNotFoundById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cannot find any term.
        /// </summary>
        internal static string TermNotFound {
            get {
                return ResourceManager.GetString("TermNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cannot find any term with corresponding id: {0}.
        /// </summary>
        internal static string TermNotFoundById {
            get {
                return ResourceManager.GetString("TermNotFoundById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Додатковий текст не може перевищувати {0} символів.
        /// </summary>
        internal static string TextAdditionalTextTooLong {
            get {
                return ResourceManager.GetString("TextAdditionalTextTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Зміст тексту є обов&apos;язковим.
        /// </summary>
        internal static string TextContentRequired {
            get {
                return ResourceManager.GetString("TextContentRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Зміст тексту не може перевищувати {0} символів.
        /// </summary>
        internal static string TextContentTooLong {
            get {
                return ResourceManager.GetString("TextContentTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Дані тексту не можуть бути порожніми.
        /// </summary>
        internal static string TextDataRequired {
            get {
                return ResourceManager.GetString("TextDataRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ID тексту має бути більше 0.
        /// </summary>
        internal static string TextIdMustBeGreaterThanZero {
            get {
                return ResourceManager.GetString("TextIdMustBeGreaterThanZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cannot find any text.
        /// </summary>
        internal static string TextNotFound {
            get {
                return ResourceManager.GetString("TextNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cannot find text with corresponding id: {0}.
        /// </summary>
        internal static string TextNotFoundById {
            get {
                return ResourceManager.GetString("TextNotFoundById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Text was not parsed successfully.
        /// </summary>
        internal static string TextParsingFailed {
            get {
                return ResourceManager.GetString("TextParsingFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Заголовок тексту є обов&apos;язковим.
        /// </summary>
        internal static string TextTitleRequired {
            get {
                return ResourceManager.GetString("TextTitleRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Заголовок тексту не може перевищувати {0} символів.
        /// </summary>
        internal static string TextTitleTooLong {
            get {
                return ResourceManager.GetString("TextTitleTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Відео повинно бути з YouTube.
        /// </summary>
        internal static string TextVideoMustBeYouTube {
            get {
                return ResourceManager.GetString("TextVideoMustBeYouTube", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cannot find any timelineItem.
        /// </summary>
        internal static string TimelineItemNotFound {
            get {
                return ResourceManager.GetString("TimelineItemNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cannot find a timeline item with corresponding id: {0}.
        /// </summary>
        internal static string TimelineItemNotFoundById {
            get {
                return ResourceManager.GetString("TimelineItemNotFoundById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cannot find any timeline item by the streetcode id: {0}.
        /// </summary>
        internal static string TimelineItemNotFoundByStreetcodeId {
            get {
                return ResourceManager.GetString("TimelineItemNotFoundByStreetcodeId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Назва не може перевищувати {0} символів.
        /// </summary>
        internal static string TitleTooLong {
            get {
                return ResourceManager.GetString("TitleTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на This toponym is already linked to the streetcode..
        /// </summary>
        internal static string ToponymAlreadyLinked {
            get {
                return ResourceManager.GetString("ToponymAlreadyLinked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Target toponym with Id={0} not found..
        /// </summary>
        internal static string ToponymByIdMerge {
            get {
                return ResourceManager.GetString("ToponymByIdMerge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cannot map StreetcodeToponymDto to entity..
        /// </summary>
        internal static string ToponymCantBeMapped {
            get {
                return ResourceManager.GetString("ToponymCantBeMapped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cannot find any toponym with corresponding id: {0}.
        /// </summary>
        internal static string ToponymNotFoundById {
            get {
                return ResourceManager.GetString("ToponymNotFoundById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cannot find any toponym by the streetcode id: {0}.
        /// </summary>
        internal static string ToponymNotFoundByStreetcodeId {
            get {
                return ResourceManager.GetString("ToponymNotFoundByStreetcodeId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Failed to create streetcode-toponym relationship..
        /// </summary>
        internal static string ToponymStreetcodeFailedToCreate {
            get {
                return ResourceManager.GetString("ToponymStreetcodeFailedToCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cannot find relationship with StreetcodeId={0} and ToponymId={1}.
        /// </summary>
        internal static string ToponymStreetcodeRelationsDelete {
            get {
                return ResourceManager.GetString("ToponymStreetcodeRelationsDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cannot find any transaction link.
        /// </summary>
        internal static string TransactionLinkNotFound {
            get {
                return ResourceManager.GetString("TransactionLinkNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cannot find any transaction link with corresponding id: {0}.
        /// </summary>
        internal static string TransactionLinkNotFoundById {
            get {
                return ResourceManager.GetString("TransactionLinkNotFoundById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cannot find a transaction link by streetcode id: {0}, because such streetcode doesn&apos;t exist.
        /// </summary>
        internal static string TransactionLinkNotFoundByStreetcodeId {
            get {
                return ResourceManager.GetString("TransactionLinkNotFoundByStreetcodeId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на User already exists.
        /// </summary>
        internal static string UserAlreadyExists {
            get {
                return ResourceManager.GetString("UserAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Дані користувача є обов&apos;язковими.
        /// </summary>
        internal static string UserDataRequired {
            get {
                return ResourceManager.GetString("UserDataRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Email має не вірний формат.
        /// </summary>
        internal static string UserEmailInvalidFormat {
            get {
                return ResourceManager.GetString("UserEmailInvalidFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не вірний email або пароль.
        /// </summary>
        internal static string UserEmailOrPasswordInvalid {
            get {
                return ResourceManager.GetString("UserEmailOrPasswordInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Email є обов&apos;язковий.
        /// </summary>
        internal static string UserEmailRequired {
            get {
                return ResourceManager.GetString("UserEmailRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Email не може перевищувати {0} символів.
        /// </summary>
        internal static string UserEmailTooLong {
            get {
                return ResourceManager.GetString("UserEmailTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Логін може містити тільки латинські літери, цифри, крапку, дефіс і підкреслення.
        /// </summary>
        internal static string UserLoginInvalidFormat {
            get {
                return ResourceManager.GetString("UserLoginInvalidFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Логін є обов&apos;язковий.
        /// </summary>
        internal static string UserLoginRequired {
            get {
                return ResourceManager.GetString("UserLoginRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Логін не може перевищувати {0} символів.
        /// </summary>
        internal static string UserLoginTooLong {
            get {
                return ResourceManager.GetString("UserLoginTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ім&apos;я користувача є обов&apos;язковим.
        /// </summary>
        internal static string UserNameRequired {
            get {
                return ResourceManager.GetString("UserNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ім&apos;я не може перевищувати {0} символів.
        /// </summary>
        internal static string UserNameTooLong {
            get {
                return ResourceManager.GetString("UserNameTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пароль повинен містити щонайменше одну малу, одну велику літеру і одну цифру.
        /// </summary>
        internal static string UserPasswordInvalidFormat {
            get {
                return ResourceManager.GetString("UserPasswordInvalidFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пароль є обов&apos;язковий.
        /// </summary>
        internal static string UserPasswordRequired {
            get {
                return ResourceManager.GetString("UserPasswordRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пароль не може перевищувати {0} символів.
        /// </summary>
        internal static string UserPasswordTooLong {
            get {
                return ResourceManager.GetString("UserPasswordTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пароль має містити як мінімум {0} символів.
        /// </summary>
        internal static string UserPasswordTooShort {
            get {
                return ResourceManager.GetString("UserPasswordTooShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Номер телефону повинен бути у міжнародному форматі (наприклад, +кодкраїниXXXXXXXXX).
        /// </summary>
        internal static string UserPhoneNumberInvalidFormat {
            get {
                return ResourceManager.GetString("UserPhoneNumberInvalidFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Failed to assign role: {0}.
        /// </summary>
        internal static string UserRoleAssignmentFailed {
            get {
                return ResourceManager.GetString("UserRoleAssignmentFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Невірна роль користувача.
        /// </summary>
        internal static string UserRoleInvalid {
            get {
                return ResourceManager.GetString("UserRoleInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Прізвище не може перевищувати {0} символів.
        /// </summary>
        internal static string UserSurnameTooLong {
            get {
                return ResourceManager.GetString("UserSurnameTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на One or more validation failures have occurred..
        /// </summary>
        internal static string ValidationException {
            get {
                return ResourceManager.GetString("ValidationException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на SendEmailAsync should be called once.
        /// </summary>
        internal static string VerifyEmailSentOnce {
            get {
                return ResourceManager.GetString("VerifyEmailSentOnce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на GetAllAsync method should be called exactly once.
        /// </summary>
        internal static string VerifyGetAllAsyncCalledOnce {
            get {
                return ResourceManager.GetString("VerifyGetAllAsyncCalledOnce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на GetFirstOrDefaultAsync method should be called exactly once.
        /// </summary>
        internal static string VerifyGetFirstOrDefaultAsyncCalledOnce {
            get {
                return ResourceManager.GetString("VerifyGetFirstOrDefaultAsyncCalledOnce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на LogError method should be called exactly once when timelineItems is null.
        /// </summary>
        internal static string VerifyLogCalledOnceTimelineNull {
            get {
                return ResourceManager.GetString("VerifyLogCalledOnceTimelineNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на LogError method should not be called when timelineItems exists.
        /// </summary>
        internal static string VerifyLogDidntCalledWhenTimelineexists {
            get {
                return ResourceManager.GetString("VerifyLogDidntCalledWhenTimelineexists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на LogError should not be called when email sent successfully.
        /// </summary>
        internal static string VerifyLoggerCalledEmailSentSuccess {
            get {
                return ResourceManager.GetString("VerifyLoggerCalledEmailSentSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на LogError method should be called exactly once when email sending fails.
        /// </summary>
        internal static string VerifyLoggerCalledOnceEmailSentFail {
            get {
                return ResourceManager.GetString("VerifyLoggerCalledOnceEmailSentFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Map method should be called exactly once.
        /// </summary>
        internal static string VerifyMapperCalledOnce {
            get {
                return ResourceManager.GetString("VerifyMapperCalledOnce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на because SaveChanges should be called after updating partner and after modifying streetcode links.
        /// </summary>
        internal static string VerifySaveChangesCalledPartnerStreetcode {
            get {
                return ResourceManager.GetString("VerifySaveChangesCalledPartnerStreetcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на because SaveChanges should be called after creating partner and after adding streetcodes.
        /// </summary>
        internal static string VerifySaveChangesCalledTwicePartnerStreetcode {
            get {
                return ResourceManager.GetString("VerifySaveChangesCalledTwicePartnerStreetcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cannot find a video with corresponding id: {0}.
        /// </summary>
        internal static string VideoNotFoundById {
            get {
                return ResourceManager.GetString("VideoNotFoundById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cannot find any videos.
        /// </summary>
        internal static string VideosNotFound {
            get {
                return ResourceManager.GetString("VideosNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Невірна структура JSON.
        /// </summary>
        internal static string WrongJSONStructure {
            get {
                return ResourceManager.GetString("WrongJSONStructure", resourceCulture);
            }
        }
    }
}
